version: '3'

services:
  api:
    build:
      context: ../..
      dockerfile: ./docker/local/Dockerfile
    env_file:
      - ./.env
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    command:
      - /entrypoint.sh
    volumes:
      - ../../.:/app

  postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
