# Generated by Django 4.1.4 on 2022-12-16 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=128)),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AlertMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullText', models.CharField(max_length=16384)),
                ('summary', models.CharField(max_length=2048)),
                ('summaryItemColor', models.CharField(max_length=8)),
                ('suspiciousKeywords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='open_ai_integration.suspiciouskeyword')),
            ],
        ),
    ]
